### ISSUE TITLE
Dockerfiles all use the same repository.

### ISSUE THREAD

**Issue by huslage** [ianmiell/shutit-distro#1]
I'm trying to understand why all of your Dockerfiles use the same repository and appear to be tagged to an automated build on Docker Hub that ends up making an essentially useless set of images.

**Comment by ianmiell** [comment]
It's CI. Every time a change is made, the modules are rebuilt.

Well, that's the theory anyway - the registry automated build is buggy and
times out. But most build in time.

They use the same repo so that the build is fully traceable; I talk about
this more here:
https://www.youtube.com/watch?v=UGp16yvSrFE&list=PL-JvSFEhoWGefxOVgfUy7Il5eLw8gFx07&index=3

**Comment by ianmiell** [comment]
Deleted shutit-distro repo as it's using resources better used by others.
